using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Services;
using System.Web.Script.Services;
using System.Web.Script.Serialization;
using System.Runtime.Serialization.Json;
using System.IO;





                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
namespace WebApplication13                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
{                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
    /// <summary>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
    /// Summary description for WebService1                                                                                                                                                                                                                                                                                                                                                                                                                                                        
    /// </summary>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
    [WebService(Namespace = "http://tempuri.org/")]                                                                                                                                                                                                                                                                                                                                                                                                                                            
    [WebServiceBinding(ConformsTo = WsiProfiles.BasicProfile1_1)]                                                                                                                                                                                                                                                                                                                                                                                                                                   
    [System.ComponentModel.ToolboxItem(false)]                                                                                                                                                                                                                                                                                                                                                                                                                                                      
    [System.Web.Script.Services.ScriptService]                                                                                                                                                                                                                                                                                                                                                                                                                                                      
    public class WebService1 : System.Web.Services.WebService                                                                                                                                                                                                                                                                                                                                                                                                                                       
    {

        public class JSONMessage
        {
            private string _payload = "";
            private string _errorMsg = "";

            // Declare a Name property of type string:
            public string payload
            {
                get
                {
                    return _payload;
                }
                set
                {
                    _payload = value;
                }
            }

            // Declare a Age property of type int:
            public string errorMsg
            {
                get
                {
                    return _errorMsg;
                }
                set
                {
                    _errorMsg = value;
                }
            }

        }                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
         
        [WebMethod]
        [ScriptMethod(ResponseFormat = ResponseFormat.Json)]

        public void HelloJson()
        {
            JavaScriptSerializer js = new JavaScriptSerializer();
            JSONMessage p = new JSONMessage();
            p.payload = "eric";
            p.errorMsg = "";
            var retval = js.Serialize(p);
            Context.Response.Write(retval);
        }


        [WebMethod]
        [ScriptMethod(ResponseFormat = ResponseFormat.Json)]
        public void HelloWorldWithJson(string name)
        {

           //JavaScriptSerializer js = new JavaScriptSerializer();
           JSONMessage p = new JSONMessage();
           p.payload  = "jon";
           p.errorMsg = "";   
           //var retval = js.Serialize(p.payload);
           //Context.Response.Write(retval);

           //Person p = new Person();
           //Set up Person object...
           MemoryStream ms = new MemoryStream();
           DataContractJsonSerializer ser = new DataContractJsonSerializer(typeof(JSONMessage));
           ser.WriteObject(ms, p);
           Context.Response.Write(p);


        }
    


      

                                                                                                                                                                                                                                                                                                                                                                                                                                                           
        [WebMethod]
        [ScriptMethod(ResponseFormat = ResponseFormat.Json)]                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
        public void GetZorkText()                                                                                                                                                                                                                                                                                                                                                                                                                                                                
        {


            string data2 =
                "Zork I- Great Underground Empire                                                                                                                                                                                                                                                                                                                                                                                                                                                   " + "\n" +
                "ZORK I Part One                                                                                                                                                                                                                                                                                                                                                                                                                                                                    " + "\n" +
                "So, you're all set for The Great Underground Empire, eh? Okay, but before we begin, a few words about this walkthru. First, this is not the only way to solve the game. It's just one of the faster ones. Second, because there is no -wasted motion- in this game, you will not be visiting all the locations. So, you might want to play around with the game on your own for a while, mapping out as                                                                            " + "\n" +
                "much as you can, without much regard for gathering treasures.                                                                                                                                                                                                                                                                                                                                                                                                                      " + "\n" +
                "Actually, mapping is a good idea, since, if you make a misstep somewhere, you might find yourself in trouble! Be especially careful to follow the directions when in the mazes; a wrong move there, and you could be lost for quite some time!                                                                                                                                                                                                                                     " + "\n" +
                "Finally, you may not go through this in exactly the way it's written because of the thief. He is a variable item in the game; you never know where he will show up. Try to move out of the room he's in as soon as he shows up. But keep in mind that even if he does steal anything from you, you will get it all back from him in the end. Okay? Let's start the adventure!                                                                                                      " + "\n" +
                "You begin West of the house, and your first chore is to get inside. So, go South and East. Open the window and enter the house (you're in the kitchen), then go West into the living room. Get the lamp, then move the rug, revealing the trap door. Open the trap door, turn on the lamp, and go down. At this point, some mysterious person will shut the door on you; don't worry about that for now.                                                                           " + "\n" +
                "Okay, so here you are in the cellar. It's time to pick up your first treasure, so go South, then East to the Gallery. Get the painting, then continue North to the Studio. Go up the chimney (you can only fit with the lamp and the painting), and you will be in the kitchen again. Now, go upstairs to the attic, and get the knife and rope. Come back down and go into the living room.                                                                                       " + "\n" +
                "Open the case and put the painting inside. Then, drop the knife and get the sword. Open the trap door again, and return to the cellar. Again, the door is shut by someone (you never will find out who's doing this, but it doesn't matter). Now you're back in the cellar, and since we're coming to one of the more dangerous parts of the game, you might want to do a save here.                                                                                               " + "\n" +
                "Gripping your trusty sword, head North into the Troll room. There's a nasty troll here with a bloody axe, and the only way past is to kill him. So, do just that- -Kill Troll With Sword.- It will most likely take more than one attempt, so keep at it, and eventually he will disappear in a cloud of black smoke. Now, drop the sword, because you really don't need it any more, and it will hinder you in carrying other, more important items.                              " + "\n" +
                "Having dispatched the troll, you move along East, East (into the Round room), then SE and East. You are now in the Dome room. It's a long way down, and too far to jump, so here's where the rope comes in handy. Tie the rope to the railing, then climb down the rope. You will be in the Torch room. Leave the torch for now; you'll be coming back this way again later.                                                                                                       " + "\n" +
                "From the Torch room, go South, then East and get the coffin. Return West, then continue South to the Altar. There's no way you're going to get down                                                                                                                                                                                                                                                                                                                                " + "\n" +
                "that hole with the coffin, and even the program will tell you that you haven't got a prayer. That's a hint, folks- Just -Pray,- and you will find yourself in the forest again. Since it's daylight out, save energy and turn off the lamp.                                                                                                                                                                                                                                        " + "\n" +
                "Now, head along South, then North (I know, but it works!) to the clearing, then East to the Canyon View. Climb all the way down to the bottom, then go North to Rainbow's End. Drop the coffin and open it. Inside is a jeweled sceptre. Get that, and wave it. The rainbow will become solid (you'll need to cross over from the other side later). Now, -Look.- You should see a pot of gold. Get that, and the coffin.                                                          " + "\n" +
                "After that, go SW, then all the way back up to Canyon View. From there, it's NW to the clearing, and then West to the window. Once in the kitchen, open the bag and get the garlic (nothing else, just the garlic). Go on into the living room, and put your treasures in the case. Now, sit down and take a breather, because you're about to do a lot of traveling!                                                                                                              " + "\n" +
                "ZORK I Part Two                                                                                                                                                                                                                                                                                                                                                                                                                                                                    " + "\n" +
                "Once again, open the trap door, turn on the lamp, and go down. Watch carefully, and you will notice that this time, the door doesn't close! Whoever was doing it before must have gotten bored. Anyway, you're on your way to the dam, so move along North, East, North, NE, and East. You are now on top of the dam.                                                                                                                                                              " + "\n" +
                "From there, go North to the Lobby. Pick up the matches, then go either North or East (doesn't matter) into the Maintenance room. Get the wrench and the screwdriver, then push the yellow button. Now, return to the dam, and you will see that the green bubble is lit. Turn the bolt with the wrench, then drop the wrench. You have opened the dam, and you will be coming back this way again to reap the fruits of your labors.                                               " + "\n" +
                "However, right now, you're on your way to Hades, so let's get going!                                                                                                                                                                                                                                                                                                                                                                                                               " + "\n" +
                "Go South, then down into the Loud room. Leave the platinum bar for now; you'll get it later. Head West into the Round room, then SE and East (hmmmm, haven't you been here before?). Again, climb down the rope. This time, get the torch. At this point, you can turn off your lamp; the torch will provide light so long as you have it.                                                                                                                                         " + "\n" +
                "Now, continue straight South, getting the bell, then the book and candles from the altar. Go down the hole to the cave, then down again to the entrance to Hades. Your candles will have blown out by this time, but don't worry about it. Okay, here's where you have to be careful. First, ring the bell. It will become red hot and you will drop it. You will also drop the candles. Stay calm, and do the following, all in one command-                                      " + "\n" +
                "Get the candles, light match, light candles with match (necessary, because of the torch, and *DON'T* use the torch, or you'll vaporize the candles!). Okay, strange things happened when you lit the candles, now read the book. Whew! The demons have been exorcised!                                                                                                                                                                                                             " + "\n" +
                "Drop the book, then go South and get the crystal skull. Now, back North, then up to the cave, then North to the Mirror room. By the way, better put out the candles. Rub the mirror, and you will now be in another Mirror room (this one is North of the dam, as the other one is South).                                                                                                                                                                                         " + "\n" +
                "Now, go North, then West, then North, then West into the Squeaky room (well, I told you you'd be doing a lot of traveling this time!). Make sure you have the garlic with you, then go North into the Bat room. So long as you have the garlic, he won't bother you. There is a jade figurine here, but leave it for now. You'll pick it up on your way out.                                                                                                                       " + "\n" +
                "ZORK I Part Three                                                                                                                                                                                                                                                                                                                                                                                                                                                                  " + "\n" +
                "Go East to the Shaft room. Put the torch into the basket, then turn on your lamp and head North to the Smelly room, then down to the Gas Room (best not to carry any open flames here!). Now, you are about to enter a small maze, so follow these directions *CAREFULLY*!                                                                                                                                                                                                         " + "\n" +
                "* East                                                                                                                                                                                                                                                                                                                                                                                                                                                                             " + "\n" +
                "* Northeast                                                                                                                                                                                                                                                                                                                                                                                                                                                                        " + "\n" +
                "* Southeast                                                                                                                                                                                                                                                                                                                                                                                                                                                                        " + "\n" +
                "* Southwest                                                                                                                                                                                                                                                                                                                                                                                                                                                                        " + "\n" +
                "* down, and you should be at the top of the ladder (if you aren't, may God have mercy on your soul!).                                                                                                                                                                                                                                                                                                                                                                              " + "\n" +
                "* From there, go down to the Ladder Bottom                                                                                                                                                                                                                                                                                                                                                                                                                                         " + "\n" +
                "* and then South to the Dead End for the coal.                                                                                                                                                                                                                                                                                                                                                                                                                                     " + "\n" +
                "* Get that, then return to the ladder top.                                                                                                                                                                                                                                                                                                                                                                                                                                         " + "\n" +
                "* From there, go up                                                                                                                                                                                                                                                                                                                                                                                                                                                                " + "\n" +
                "* North                                                                                                                                                                                                                                                                                                                                                                                                                                                                            " + "\n" +
                "* East                                                                                                                                                                                                                                                                                                                                                                                                                                                                             " + "\n" +
                "* South                                                                                                                                                                                                                                                                                                                                                                                                                                                                            " + "\n" +
                "* North, and you will be back in the Gas room                                                                                                                                                                                                                                                                                                                                                                                                                                      " + "\n" +
                "* Go up, then South to the Shaft room again.                                                                                                                                                                                                                                                                                                                                                                                                                                       " + "\n" +
                "Put the coal in the basket, and lower the basket. Now, guess what? You have to go back through the coal mine again! So, make your way to the Ladder Bottom, but this time, go West to the Timber room. Ignore the broken timber (not useful for anything), and drop all but the screwdriver. Now, you can squeeze through the crack to the West.                                                                                                                                   " + "\n" +
                "And here you are in the Drafty Room, which is also at the bottom of the shaft. There's the basket, so get the coal and the torch, and move South into the Machine room. Open the lid, put the coal in the machine, close the lid, and turn the switch with the screwdriver. Drop the screwdriver, open the lid, and get the diamond (well, no one ever said Zork was an *EASY* game!). Now, go back North, and put the torch and the diamond in the basket.                        " + "\n" +
                "Squeeze back East into the Timber room. Get the skull, lamp, and garlic. You won't be needing the matches and the candles any more, so you can leave them. (They were insurance in case the thief came along and stole the torch before you could get the diamond). Now, head East again to the Ladder Bottom, and from there up and through the coal mine (you know the way now!), to the Gas room. Pick up the bracelet, then continue on up and South to the Shaft room.        " + "\n" +
                "Get the torch and the diamond from the basket, turn off the lamp, then go West into the Bat room. Get the jade, then go South, East, South to the Slide room.                                                                                                                                                                                                                                                                                                                      " + "\n" +
                "Now, here's a fast way back to the cellar- Just go down the slide! Wheeeee! Then it's up to the living room (remember, the trap door is open now), and all the treasures go into the case. Huff! Puff! Bet you didn't know you'd be doing *THIS* much running around! But, don't get too relaxed, there's still plenty more to come (urk!).                                                                                                                                        " + "\n" +
                "ZORK I Part Four                                                                                                                                                                                                                                                                                                                                                                                                                                                                   " + "\n" +
                "Turn on the lamp, and return to the cellar. From there, it's North (ah, deja vu!), then East, North, NE to Reservoir South. Now that the sluice gates are open, you can head North, picking up the trunk of jewels, North again to Reservoir North, getting the air pump, and North one more time, getting the crystal trident. After that, go all the way back South again to Reservoir South, then East to the dam, and then East once more to the Dam Base.                     " + "\n" +
                "Here you find a little pile of folded plastic; guess what it is? Right, it's an inflatable boat! So, inflate it with the pump, then drop the pump, then get inside the boat, say -Launch,- and you're floating off along the Frigid River.                                                                                                                                                                                                                                         " + "\n" +
                "Now, just keep waiting until you see the buoy. Get that, then -East- to the beach. Get out of the boat, then get the shovel and move on to the Sandy Cave to the NE. You might want to save the game at this point, since you have to dig here until the scarab turns up, and I'm sure you don't want to get buried alive (it's been known to happen!). Okay, drop the shovel and get the scarab, then go back SW. Drop the buoy and open it; inside is an emerald.                " + "\n" +
                "Get that, then continue South to the Aragain Falls.                                                                                                                                                                                                                                                                                                                                                                                                                                " + "\n" +
                "Here you can cross the rainbow (so do that!), which brings you to the End of The Rainbow. Turn off the lamp, then go SW to the Canyon Bottom. From there, make your way back to the living room, and put all the treasures in the case. Your collection is quite impressive by now, but you aren't finished yet. Go East twice, then North twice. Climb up the tree and get the egg. Climb down again, and go South, East, and back to the living room. However,                   " + "\n" +
                "this time, you don't put the treasure in the case.                                                                                                                                                                                                                                                                                                                                                                                                                                 " + "\n" +
                "Turn on the lamp, and go down (once again!) into the cellar, and North to the Troll room. Now, you are about to enter a maze, so follow the directions very carefully!                                                                                                                                                                                                                                                                                                             " + "\n" +
                "* West (this brings you into the maze)                                                                                                                                                                                                                                                                                                                                                                                                                                             " + "\n" +
                "* South                                                                                                                                                                                                                                                                                                                                                                                                                                                                            " + "\n" +
                "* East, up, and you find several items here                                                                                                                                                                                                                                                                                                                                                                                                                                        " + "\n" +
                "* Take only the coins and the key, and be careful not to touch the skeleton!                                                                                                                                                                                                                                                                                                                                                                                                       " + "\n" +
                "* From here, go SW                                                                                                                                                                                                                                                                                                                                                                                                                                                                 " + "\n" +
                "* East                                                                                                                                                                                                                                                                                                                                                                                                                                                                             " + "\n" +
                "* South                                                                                                                                                                                                                                                                                                                                                                                                                                                                            " + "\n" +
                "* SE, and you will be in the Cyclops room. The Cyclops is not friendly, but you can deal with him effortlessly- Just type in -Ulysses- (or -Odysseus,- if you prefer). Old One-Eye will tear out of there right through the wall! In fact, he will create a passage eastward from that room right into the living room!                                                                                                                                                            " + "\n" +
                "However, you don't want to go that way yet! Instead, go upstairs, and you will be in the Treasure Room, the thief's secret lair. Now, give him the egg, and go back downstairs, then East to the living room. Deposit the coins in the case, then get the knife (the thief needs a little time to open the egg). Okay, go back West to the Cyclops room. Again, at this point, saving is recommended; the thief will not be easy to kill!                                          " + "\n" +
                "So, head upstairs and use the nasty knife to kill the thief. Once he's dead, all treasures in the room will be visible. This includes the egg, a silver chalice, and anything he may have stolen from you before. Get everything, then follow these directions- Down, NW, South, West, up, down, NE, and you will be in the Grating Room. Unlock and open the grate (watch out for falling leaves!), then go up. You will be in a clearing. From there,                            " + "\n" +
                "go South and climb the tree again. Wind up the canary that's inside the egg. A songbird will come by and drop a bauble for you. Climb down again and get the bauble, then return to the living room. Put all the treasures in the case, making sure you *REMOVE THE CANARY* from the egg and put it in the case separately! You're almost finished! Just one more trip to make!                                                                                                    " + "\n" +
                "Now, for the last time, enter the cellar and go North. From the Troll Room, go East until you come again to the Loud Room. Type in- -Echo,- and you will now be able to get the bar. So, grab it and return to the living room. Once you place it in the case, you will get a message. Follow the advice of that message, and you will get a map. Take that, and return to the place where this all started, the mailbox West of the house.                                        " + "\n" +
                "You should have no trouble getting to the barrow from there. Of course, once you enter the barrow....                                                                                                                                                                                                                                                                                                                                                                              " + "\n" +
                "You didn't really think it would end there, did you? Not when there's still Zork II and Zork III waiting for you up ahead! Ah, but it's too late; you can't turn back now! You'll just have to grit your teeth and follow through to the end (with a little help, of course). See you in Zork II!                                                                                                                                                                                  " + "\n";

            JSONMessage msg = new JSONMessage();

            msg.payload = data2;
            msg.errorMsg = "";
            //return data; 


            JavaScriptSerializer js = new JavaScriptSerializer();
            var retval = js.Serialize(msg);
            Context.Response.Write(retval);

        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
        [WebMethod]
        [ScriptMethod(ResponseFormat = ResponseFormat.Json)]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
        public void GetTextStatistics( string paragraph ,                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                       string filter)                                                                                                                                                                                                                                                                                                                                                                                                                                           
        {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
            if ((filter == "")||(filter=="undefined"))                                                                                                                                                                                                                                                                                                                                                                                                                                            
            {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                filter = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";                                                                                                                                                                                                                                                                                                                                                                                                                                            
            }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
            Dictionary<string, int> dict = new Dictionary<string, int>();                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
            filter = filter.ToUpper();                                                                                                                                                                                                                                                                                                                                                                                                                                                           
            filter = filter.Replace(" ", "");                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
            //BUILD A ZERO INDEXED FILTER LIST                                                                                                                                                                                                                                                                                                                                                                                                                                                  
            for (int i=0 ; i < filter.Length ; i++ )                                                                                                                                                                                                                                                                                                                                                                                                                                            
            {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                //ONLY ADD KEYS IF THEY ARE ALPHA AND DONT ALREADY EXIST                                                                                                                                                                                                                                                                                                                                                                                                                        
                string key = filter.Substring(i,1).ToUpper();                                                                                                                                                                                                                                                                                                                                                                                                                                   
                if ((!dict.ContainsKey(key))&&( "ABCDEFGHIJKLMNOPQRSTUVWXYZ".IndexOf(key) > -1 )) {                                                                                                                                                                                                                                                                                                                                                                                             
                dict.Add(key , 0);                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                }                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
            }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                

            string data = paragraph ;
            //DEFENSIVE CODING INCASE THERE WAS MULTIPLE SPACES
            while (data.IndexOf("  ") > -1)
            {
            data = data.Replace("  ", " ");
            }
            data = data.Trim();
            string[] dataArray = data.Split(' ');
         
            foreach (string d in dataArray)
            {
                //SKIP EMPTY STRING
                if (d == "")
                {
                    continue;
                }

                string mykey = d.Substring(0, 1).ToUpper();

                if (dict.ContainsKey(mykey)==true)
                {
                    int i = dict[mykey];
                    i++;
                    dict[mykey] = i;
                }
                else
                {
                    dict.Add(mykey, 1);
                }
            }
            string result = "<table>";
            result = result + "<tr><td>[STARTING LETTER]</td><td>[WORD COUNT]</td></tr></tr>";

            foreach (KeyValuePair<string, int> pair in dict) {

                if (filter.ToString().Contains(pair.Key.ToString())  )
                {
                    result = result + "<tr>";
                    result = result + "<td>" + pair.Key.ToString() + "</td><td>" + pair.Value.ToString() + "</td>"; 
                    result = result + "</tr>";
                }

                }

            result = result + "</table>";


            result = "ERIC WAS HERE";


            JSONMessage msg = new JSONMessage();

            msg.payload = result;
            msg.errorMsg = "";
            //return data; 


            JavaScriptSerializer js = new JavaScriptSerializer();
            var retval = js.Serialize(msg);
            Context.Response.Write(retval);

           
        }
    }
}
